

py:
	${MAKE} -C ./python

accel:
	${MAKE} -C ./accelpy

plot:
	python slab_viewer.py python/miniweather_mpi.slab


profpy:
	${MAKE} -C ./python profile

profaccel:
	${MAKE} -C ./accelpy profile

clean:
	rm -f *.png
